[package]
name = "ivy-control-room"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.70"
sysinfo = "0.30"
